name: Build

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
      - name: Disable AppArmor
        run:
          echo 0 | sudo tee
          /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: make
